name: Run Python Script

on: [push] # Triggers the workflow on every push to the repo
  schedule:
    # This runs every day at 00:00 UTC
    - cron: '42 20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest # The environment to run on

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Specify your preferred version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        run: python primeiro.py